defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
kramdown:
  toc_levels: "1..4"
plugins:
  - jekyll-minifier
  - jekyll-feed
jekyll-minifier:
  remove_intertag_spaces: true
